<a href="https://colab.research.google.com/github/CE334/CE334_230840_Rajesh_kumar_s/blob/main/CE334_RAJESH_KUMAR_S_230840_LAB_NO_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

question 1

In [1]:
# Take input for a row vector
row = list(input("Enter elements of row vector separated by space: ").split())

# Convert row vector to column vector by using the for loop
column = [[x] for x in row]

print("Row vector:", row)
print("Column vector:", column)


Enter elements of row vector separated by space: 3 5 6 4 
Row vector: ['3', '5', '6', '4']
Column vector: [['3'], ['5'], ['6'], ['4']]


In [32]:
# Manually defined vectors
row_manual = [5, 7, 3]
column_manual = [[5], [7], [3]]

print("Row vector (manual):", row_manual)
print("Column vector (manual):", column_manual)


Row vector (manual): [5, 7, 3]
Column vector (manual): [[5], [7], [3]]


question 2

In [3]:
a = [] # we initialize an empty list, later we will use the .append() function to add the inputed numbers row by row.

print("Enter the 5×5 matrix row by row:")
for i in range(5):
    row = list(input().split()) # here we use the for loop to take the input numbers row by row.
    a.append(row)

print("Matrix a:")
for row in a:
    print(row)# here we will print the matrix a


Enter the 5×5 matrix row by row:
3 3 3 3 3
2 1 3 2 1
8  3 3 8 9
7 7 7 7 7
8 8 7 3 7
Matrix a:
['3', '3', '3', '3', '3']
['2', '1', '3', '2', '1']
['8', '3', '3', '8', '9']
['7', '7', '7', '7', '7']
['8', '8', '7', '3', '7']


In [30]:
a = [
    [10, 2, 3, 4, 5],
    [1, 20, 3, 4, 5],
    [1, 2, 30, 4, 5],
    [1, 2, 3, 40, 5],
    [1, 2, 3, 4, 50]
]# here all the entries are hard coded manually.

print("Matrix a:")
for row in a:
    print(row)


Matrix a:
[10, 2, 3, 4, 5]
[1, 20, 3, 4, 5]
[1, 2, 30, 4, 5]
[1, 2, 3, 40, 5]
[1, 2, 3, 4, 50]


question 3

In [31]:
third_row = a[2]   # index starts from 0
print("3rd row of matrix a:", third_row)


3rd row of matrix a: [1, 2, 30, 4, 5]


question 4

In [19]:
import numpy as np

a = np.array([
    [10, 2, 3, 4, 5],
    [1, 20, 3, 4, 5],
    [1, 2, 30, 4, 5],
    [1, 2, 3, 40, 5],
    [1, 2, 3, 4, 50]
])


In [20]:
fourth_column = a[:, 3]   # index starts from 0
print("4th column:", fourth_column)


4th column: [ 4  4  4 40  4]


question 5

In [21]:
row_sorted = np.sort(a, axis=1) # here we are using the np.sort function to sort the elements in the rows. also we set axis = 1 which means sort along the rows
print("Row-wise sorted matrix:\n", row_sorted)


Row-wise sorted matrix:
 [[ 2  3  4  5 10]
 [ 1  3  4  5 20]
 [ 1  2  4  5 30]
 [ 1  2  3  5 40]
 [ 1  2  3  4 50]]


In [22]:
column_sorted = np.sort(a, axis=0) # here also we will be using the np.sort function. and the change here is that the axis = 0, which is along the columns
print("Column-wise sorted matrix:\n", column_sorted)


Column-wise sorted matrix:
 [[ 1  2  3  4  5]
 [ 1  2  3  4  5]
 [ 1  2  3  4  5]
 [ 1  2  3  4  5]
 [10 20 30 40 50]]


question 6

In [23]:
b = a.copy() # here we use the .copy() function to copy the matrix a, so that later changes will not make any changes in a.

for i in range(a.shape[0]):
    for j in range(a.shape[1]):# using the nested for loops to iterate through the matrix a and check for the condition and change the element accordingly.
        if a[i, j] > 2:
            b[i, j] = a[i, j] * 10

print("Matrix b:\n", b)


Matrix b:
 [[100   2  30  40  50]
 [  1 200  30  40  50]
 [  1   2 300  40  50]
 [  1   2  30 400  50]
 [  1   2  30  40 500]]


question 7

In [24]:
add_result = a + b # this operation will do element wise addition. note that this will not work, if we use the normal python lists
print("a + b:\n", add_result)


a + b:
 [[110   4  33  44  55]
 [  2 220  33  44  55]
 [  2   4 330  44  55]
 [  2   4  33 440  55]
 [  2   4  33  44 550]]


question 8

In [25]:
sub_result = a - b # here also this operation will do element wise substraction.
print("a - b:\n", sub_result)


a - b:
 [[ -90    0  -27  -36  -45]
 [   0 -180  -27  -36  -45]
 [   0    0 -270  -36  -45]
 [   0    0  -27 -360  -45]
 [   0    0  -27  -36 -450]]


question 9

In [26]:
elementwise_mul = a * b # element wise multiplication
print("Element-wise multiplication:\n", elementwise_mul)


Element-wise multiplication:
 [[ 1000     4    90   160   250]
 [    1  4000    90   160   250]
 [    1     4  9000   160   250]
 [    1     4    90 16000   250]
 [    1     4    90   160 25000]]


In [27]:
matrix_mul = np.dot(a, b) # here we are using the np.dot to do the dot product of the matrix a,b.
print("Matrix multiplication:\n", matrix_mul)


Matrix multiplication:
 [[ 1014   444  1530  2400  3450]
 [  132  4026  1800  2760  3900]
 [  141   480  9360  3120  4350]
 [  150   498  2340 16440  4800]
 [  159   516  2610  3840 25500]]


question 10

In [28]:
a_div = a / 18# here we will divide every element in the matrix a by 18
b_div = b / 18# same with the matrix b

print("a divided by 18:\n", a_div)
print("b divided by 18:\n", b_div)


a divided by 18:
 [[0.55555556 0.11111111 0.16666667 0.22222222 0.27777778]
 [0.05555556 1.11111111 0.16666667 0.22222222 0.27777778]
 [0.05555556 0.11111111 1.66666667 0.22222222 0.27777778]
 [0.05555556 0.11111111 0.16666667 2.22222222 0.27777778]
 [0.05555556 0.11111111 0.16666667 0.22222222 2.77777778]]
b divided by 18:
 [[ 5.55555556  0.11111111  1.66666667  2.22222222  2.77777778]
 [ 0.05555556 11.11111111  1.66666667  2.22222222  2.77777778]
 [ 0.05555556  0.11111111 16.66666667  2.22222222  2.77777778]
 [ 0.05555556  0.11111111  1.66666667 22.22222222  2.77777778]
 [ 0.05555556  0.11111111  1.66666667  2.22222222 27.77777778]]


question 11

In [29]:
# Inverse
a_inv = np.linalg.inv(a) # here we will use the np.linalg which is the numpy's linear algebra module which has all the matrix methods like the .inv,.svd etc
b_inv = np.linalg.inv(b)

# Rank
a_rank = np.linalg.matrix_rank(a)
b_rank = np.linalg.matrix_rank(b)

# Condition number
a_cond = np.linalg.cond(a)
b_cond = np.linalg.cond(b)

# Singular Value Decomposition
U_a, S_a, Vt_a = np.linalg.svd(a)
U_b, S_b, Vt_b = np.linalg.svd(b)

# Norm
a_norm = np.linalg.norm(a)
b_norm = np.linalg.norm(b) # here we are using the .norm function from the linalg module

print("Inverse of a:\n", a_inv)# also remember that , inverse for a matrix exist only if the determinent is not equal to zero
print("Rank of a:", a_rank)
print("Condition number of a:", a_cond)
print("Norm of a:", a_norm)


Inverse of a:
 [[ 0.1031746  -0.00793651 -0.00793651 -0.00793651 -0.00793651]
 [-0.00396825  0.0515873  -0.00396825 -0.00396825 -0.00396825]
 [-0.0026455  -0.0026455   0.03439153 -0.0026455  -0.0026455 ]
 [-0.00198413 -0.00198413 -0.00198413  0.02579365 -0.00198413]
 [-0.0015873  -0.0015873  -0.0015873  -0.0015873   0.02063492]]
Rank of a: 5
Condition number of a: 5.675081718398471
Norm of a: 75.63068160475615


question 12

In [34]:
col = np.array([[5], [7], [3]])
norm_col = np.linalg.norm(col)
print("Norm:", norm_col)


Norm: 9.1104335791443


In [35]:
inner = np.dot(col.T, col)# here we use the np.dot to find the dot product and also we use .T to find the transpose of any matrix
print("Inner product:\n", inner)


Inner product:
 [[83]]


In [36]:
outer = np.dot(col, col.T)
print("Outer product:\n", outer)


Outer product:
 [[25 35 15]
 [35 49 21]
 [15 21  9]]


question 13

In [39]:
import numpy as np

def derivative(f, a, method="central", h=0.01):# here we are using the if-elif-else condition statement to check for very condition
    if method == "forward":
        return (f(a + h) - f(a)) / h

    elif method == "backward":
        return (f(a) - f(a - h)) / h

    elif method == "central":
        return (f(a + h) - f(a - h)) / (2 * h)

    else:
        print("Invalid method")
        return None
f1 = np.exp      # e^x
f2 = np.cos     # cos(x)

x = 0.5
print("Derivative of e^x at x = 0.5:")
print("Forward :", derivative(f1, x, method="forward"))
print("Backward:", derivative(f1, x, method="backward"))
print("Central :", derivative(f1, x))   # default central

print("\nDerivative of cos(x) at x = 0.5:")
print("Forward :", derivative(f2, x, method="forward"))
print("Backward:", derivative(f2, x, method="backward"))
print("Central :", derivative(f2, x))   # default central



Derivative of e^x at x = 0.5:
Forward : 1.6569924245758205
Backward: 1.6405050744749294
Central : 1.648748749525375

Derivative of cos(x) at x = 0.5:
Forward : -0.483805424462147
Backward: -0.4750296719748692
Central : -0.4794175482185081


question 14

In [40]:
import pandas as pd
df = pd.read_csv("/content/aws_data.csv") # here we read the csv file with the pandas read_csv function.


In [41]:
print(df.head())   # shows first 5 rows


                  created_at  entry_id  Soil Temperature  Soil Moisture  \
0  2022-12-14T14:19:11+05:30     10830             21.06            817   
1  2022-12-14T14:20:13+05:30     10831             21.06            817   
2  2022-12-14T14:21:15+05:30     10832             21.06            817   
3  2022-12-14T14:22:18+05:30     10833             21.06            817   
4  2022-12-14T14:23:20+05:30     10834             21.06            817   

   Wind Speed  Rainfall  Temperature  Humidity  Pressure  Battery Voltage  
0         0.0      0.25        25.38     45.09      1.94             4.14  
1         0.0      0.25        25.27     46.52      1.94             4.14  
2         0.0      0.25        25.34     45.79      1.94             4.14  
3         0.0      0.25        25.13     44.91      1.94             4.15  
4         0.0      0.25        24.95     45.12      1.94             4.15  


In [42]:
print(df.info()) # this .info() function gives basic information about the table like the data types stored in each of the column and what is the name of each column


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 659 entries, 0 to 658
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   created_at        659 non-null    object 
 1   entry_id          659 non-null    int64  
 2   Soil Temperature  659 non-null    float64
 3   Soil Moisture     659 non-null    int64  
 4   Wind Speed        659 non-null    float64
 5   Rainfall          659 non-null    float64
 6   Temperature       659 non-null    float64
 7   Humidity          659 non-null    float64
 8   Pressure          659 non-null    float64
 9   Battery Voltage   659 non-null    float64
dtypes: float64(7), int64(2), object(1)
memory usage: 51.6+ KB
None
